POST http://192.168.11.6:5001/ask
Accetp: application/json
Content-type: application/json

{
  "messages": [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "What's next actoin on AI field?"}
  ],
  "temperature": 0.5,
  "max_tokens": 50
}

###
POST http://compes.serveo.net/ask
Accetp: application/json
Content-type: application/json

{
  "messages": [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "What's next actoin on AI field?"}
  ],
  "temperature": 0.5,
  "max_tokens": 50
}
