# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
      - name: chat-api
        image: keijijin/chat_api:v2
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: chat-api
spec:
  type: NodePort
  ports:
    - port: 5001
      nodePort: 30001
      protocol: TCP
  selector:
    app: chat-api
